### ISSUE TITLE
(tcp) Enable multi port/protocol support

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-helm-chart#34]
Tyk Gateway can now proxy TCP(s) traffic, and the gateways can listen on multiple ports.
As such, the ingress controller should be updated to reflect the same.

**Comment by excieve** [comment]
This is more for the ingress controller itself as it's a function of API definitions rather than deployment configuration. Probably requires CRDs to be usable and requires mutation of services.

For each API with a non-standard port it must be declared on the service dynamically every time API definition is changed (this is also subject to availability on the underlying infrastructure, i.e. whether a load balancer on a specific provider supports it). Raw TCP/TLS routing is not supported by k8s ingresses so most definitely needs CRDs (well, the spec can probably be abused with some annotations, but there's no standard way in k8s for this).
