### ISSUE TITLE
Create a proper chart repository

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk-helm-chart#64]
In order to introduce proper versioning/archiving and to be able to install a chart remotely we'll need a chart repository, which can be as simple as GH Pages/S3 bucket or more advanced with [Chart Museum](https://chartmuseum.com/).

More details here: https://helm.sh/docs/topics/chart_repository/

Needs automation to create chart packages and upload to the repository.

**Comment by drpebcak** [comment]
Any thoughts on this? After #69 is merged/released, I wouldn't need to maintain a fork of this chart anymore. Would be nice to install versioned releases from a helm repo instead of cloning the git repository. I've done this before using github and travis - https://github.com/FusionAuth/charts/blob/master/.travis.yml

It could also probably be done with github actions.
